### ISSUE TITLE
Introduce 'comma-dangle' rule

### ISSUE THREAD

**Issue by NehrDani** [sevencooks-gmbh-co-kg/eslint-config-sevencooks#4]
Hello @smartfood-gmbh-co-kg/frontend I want to introduce a new rule to our eslint config: [comma-dangle](https://eslint.org/docs/rules/comma-dangle).

I would prefer to allow trailing commas in objects, arrays, imports and exports.
```js
{
  "comma-dangle": ["error", {
        "arrays": "always-multiline",
        "objects": "always-multiline",
        "imports": "always-multiline",
        "exports": "always-multiline",
        "functions": "ignore",
    }]
}
```

There are some advantages here:
- easier code manipulations.
  - Copy the line of the last entry & paste it to any position except the last in the target object/array.
- Cleaner diffs.
  - With the dangling comma only the new entry is visible in the diff.

FYI: https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8

**Comment by acidicX** [comment]
we had this already when we were using the pg eslint config, so I'm for it.

**Comment by Blacklist** [comment]
same here - go for it

**Comment by moalo** [comment]
In general, I'm not a big fan of doing things that can be done but should not be done. Here I see a clear benefit. So, go for it!

**Comment by NehrDani** [comment]
We still need to publish this to NPM.

**Comment by NehrDani** [comment]
So its released and ticket for integration is open https://github.com/smartfood-gmbh-co-kg/sevencooks-webapp/pull/1985
